### ISSUE TITLE
RFC: Unit testing

### ISSUE THREAD

**Issue by brentvatne** [Flipboard/react-canvas#37]
With new pull requests being merged each day, we should look into establishing unit tests and a requirement for all pull requests to have unit tests attached, or we may start to run into regressions.

Did you have test coverage for your internal Flipboard app @mjohnston? Any preferred tooling?

**Comment by darkyen** [comment]
+1

**Comment by mjohnston** [comment]
Absolutely! Though I would hesitate to require that all PRs have unit tests attached just yet, as things are still subject to change (specifically I want to take another look at event registration).

At Flipboard, we run mocha tests in a custom test runner that can run in connected browsers or PhantomJS. Though admittedly much of the mobile web code is not covered.

I don't feel strongly about sticking with mocha. It's been awhile since I looked into it, but Jasmine seems to be generally well-liked. I'm open to suggestions if you have any.

**Comment by darkyen** [comment]
I am agnostic to both, psssh my PR#32 would of detected the error out of the box :-) if we had Unit Tests.

**Comment by mjohnston** [comment]
Closing this as the PR has been merged.

@brentvatne @darkyen If you plan to add more tests for the existing code base, one area I would stay away from is the css-layout integration. The JS version is not optimized (react-native uses the C version), and neither is the React Canvas integration. So this code is subject to being removed or heavily modified.

**Comment by brentvatne** [comment]
@mjohnston - sounds good, first stop for me will be hitTest and related modules to add coverage to your fix for #23, @darkyen perhaps you could look at adding coverage for #32?

**Comment by darkyen** [comment]
Yup, will do #32 first and then start doing css-layout integration

**Comment by mjohnston** [comment]
@darkyen I would hold off on the css-layout integration tests. (see my previous comment) Before going much further down the css-layout path we need to look at caching optimizations and proper text flow.

**Comment by darkyen** [comment]
Alright, I will head with #32 -> text flow and then decide where to from
there :-)

just read your last comment.
