### ISSUE TITLE
Style inheritance and cascading

### ISSUE THREAD

**Issue by podo** [Flipboard/react-canvas#9]
Thanks for opensourcing this, however, I do have a question. I’m not sure if anybody done this before and if it would make sense in `react-canvas` or `react-native`, but what about CSS-like inheritance and cascading of styles? Even though, everything seems like big step forward in performance and app development, styling, in my opinion, seems more complicated and difficult. Am I wrong?

**Comment by iam4x** [comment]
You can export your styles in a new file, and `require` them. Since they are only `Object` you can merge them and have inheritance.

You can do whatever you want, make a function to load your styles objects, merge them etc...?

**Comment by mjohnston** [comment]
Cascading styles are something I've tried to avoid. Not only due to the added performance cost, but it often leads to bugs where updating styles can have unexpected side effects downstream.

That being said, you might take a look at the [css-layout example](https://github.com/Flipboard/react-canvas/blob/master/examples/css-layout/app.js) to see how having a minimal subset of CSS (margins/padding/flexbox) changes the way components are styled.

**Comment by irvinebroque** [comment]
@podo - see: https://speakerdeck.com/vjeux/react-css-in-js, everything is moving in this direction right now.

**Comment by podo** [comment]
Thanks!
